"""new match

Revision ID: 2b5205d4eac0
Revises: cc82ef9c7d3d
Create Date: 2016-09-27 14:37:31.493613

"""

# revision identifiers, used by Alembic.
revision = '2b5205d4eac0'
down_revision = 'cc82ef9c7d3d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band', sa.Enum('k', 'j', 'h', name='match, bands'), nullable=True),
    sa.Column('master_src_id', sa.Integer(), nullable=False),
    sa.Column('master_src_order', sa.Integer(), nullable=True),
    sa.Column('master_src_ra', sa.Float(), nullable=True),
    sa.Column('master_src_dec', sa.Float(), nullable=True),
    sa.Column('pawprint_id', sa.Integer(), nullable=False),
    sa.Column('pawprint_src_id', sa.Integer(), nullable=False),
    sa.Column('pawprint_src_order', sa.Integer(), nullable=True),
    sa.Column('pawprint_src_ra', sa.Float(), nullable=True),
    sa.Column('pawprint_src_dec', sa.Float(), nullable=True),
    sa.Column('pawprint_src_mag', sa.Float(), nullable=True),
    sa.Column('pawprint_src_mag_err', sa.Float(), nullable=True),
    sa.Column('pawprint_src_hjd', sa.Float(), nullable=True),
    sa.Column('pawprint_src_chip_nro', sa.Float(), nullable=True),
    sa.Column('pawprint_src_stel_cls', sa.Float(), nullable=True),
    sa.Column('pawprint_src_elip', sa.Float(), nullable=True),
    sa.Column('pawprint_src_pos_ang', sa.Float(), nullable=True),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_src_id'], ['MasterSource.id'], ),
    sa.ForeignKeyConstraint(['pawprint_id'], ['Pawprint.id'], ),
    sa.ForeignKeyConstraint(['pawprint_src_id'], ['PawprintSource.id'], ),
    sa.ForeignKeyConstraint(['tile_id'], ['Tile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pawprint_src_id', 'master_src_id', 'tile_id', name='_match_uc')
    )
    op.create_index(op.f('ix_Match_band'), 'Match', ['band'], unique=False)
    op.create_index(op.f('ix_Match_master_src_id'), 'Match', ['master_src_id'], unique=False)
    op.create_index(op.f('ix_Match_pawprint_id'), 'Match', ['pawprint_id'], unique=False)
    op.create_index(op.f('ix_Match_pawprint_src_id'), 'Match', ['pawprint_src_id'], unique=False)
    op.create_index(op.f('ix_Match_tile_id'), 'Match', ['tile_id'], unique=False)
    op.create_index(op.f('ix_Tile_name'), 'Tile', ['name'], unique=True)
    op.drop_constraint(u'Tile_name_key', 'Tile', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'Tile_name_key', 'Tile', ['name'])
    op.drop_index(op.f('ix_Tile_name'), table_name='Tile')
    op.drop_index(op.f('ix_Match_tile_id'), table_name='Match')
    op.drop_index(op.f('ix_Match_pawprint_src_id'), table_name='Match')
    op.drop_index(op.f('ix_Match_pawprint_id'), table_name='Match')
    op.drop_index(op.f('ix_Match_master_src_id'), table_name='Match')
    op.drop_index(op.f('ix_Match_band'), table_name='Match')
    op.drop_table('Match')
    ### end Alembic commands ###
