# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CQLAst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast', django_extensions.db.fields.json.JSONField()),
                ('hash', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CQLQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('hash', models.CharField(max_length=255)),
                ('ast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject.CQLAst')),
                ('users', models.ManyToManyField(related_name='cql_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
