# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqlquery',
            name='counter',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
