# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_cqlquery_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cqlast',
            name='ast',
        ),
        migrations.AddField(
            model_name='cqlast',
            name='_ast',
            field=models.TextField(db_column=b'ast', default=b'null'),
        ),
    ]
