# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0004_auto_20160228_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(help_text=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.TextField(help_text=b'Why do you want a Capyncho user? (or any other commentary)'),
        ),
    ]
